const date = Date.now();
const initialTasks = [
  {
    height: '56',
    id: 'lkj645lkj5464lk456jl456',
    text: 'Example task, click to edit',
    isSwiped: false,
    isCompleted: false,
    isOpen: false,
    dateCreated: date,
    isOverdue: false,
    isDueSoon: false,
    distanceToNow: null,
    dueDate: null,
    dateCompleted: null,
    date: null,
    formattedDate: null,
  },
  {
    height: '56',
    id: '097gdf08g7d90f8g7df098g7y',
    text: 'Swipe to delete',
    isSwiped: false,
    isCompleted: false,
    isOpen: false,
    dateCreated: date,
    isOverdue: false,
    isDueSoon: false,
    distanceToNow: null,
    dueDate: null,
    dateCompleted: null,
    date: null,
    formattedDate: null,
  },
  {
    height: '56',
    id: 'kljngfifgnwrt6469fsd5ttsh',
    text: 'Drag to reorder',
    isSwiped: false,
    isCompleted: false,
    isOpen: false,
    dateCreated: date,
    isOverdue: false,
    isDueSoon: false,
    distanceToNow: null,
    dueDate: null,
    dateCompleted: null,
    date: null,
    formattedDate: null,
  },
  {
    height: '56',
    id: 'kljngfifsdfs546wsd5ttsh',
    text: 'Click the handle on the right to open',
    isSwiped: false,
    isCompleted: false,
    isOpen: false,
    dateCreated: date,
    isOverdue: false,
    isDueSoon: false,
    distanceToNow: null,
    dueDate: null,
    dateCompleted: null,
    date: null,
    formattedDate: null,
  },
];

export default initialTasks;
